#%RAML 1.0
title: HelloWorldAPI
version: v1
baseUri: http://api.example.com/helloworld
description: A simple API that returns hello world message

/helloworld:
  get:
    description: Returns a hello world message
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "helloworld"
              }
      404:
        body:
          application/json:
            example: |
              {
                "error": "Resource not found"
              }